name: .NET

on:
  push:
    branches: 
        - master
  pull_request:
    branches: 
        - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Run build script
      run: |
        cd ./src/netstandard2.0/BuildScript 
        dotnet run
